### ISSUE TITLE
Roldan Uriel Arcadio Avila 1BS Mapa mental

### ISSUE THREAD

**Issue by Roldanuriel** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Roldanuriel#1]
![Roldan Uriel Arcadio Avila 1BS Mapa Mental](https://user-images.githubusercontent.com/112295222/190885560-93bba69c-d406-427e-a4c2-63944859a16e.png)

**Comment by Jaczibeth** [comment]
Obtuviste un 17.8% del 20%
Falto presentar imágenes y presentas faltas ortográficas.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
